//
// Created by Jake on 11/16/2022.
//

#ifndef GL_RAYTRACER_LAMBERTIANDIFFUSEMATERIAL_H
#define GL_RAYTRACER_LAMBERTIANDIFFUSEMATERIAL_H


class LambertianDiffuseMaterial {

};


#endif //GL_RAYTRACER_LAMBERTIANDIFFUSEMATERIAL_H
